### PR TITLE
Add support for tsx and fix overflow issue

### PR DESCRIPTION
**Pull request by dutzi**
Hi,

This PR:

1. Fixes the overflow issue you get when pasting a long file
2. Adds support for TSX

### CODE REVIEW

**Comment by dutzi** [comment]
I tried adding a checkbox for TSX, but gave up when I got console errors like `'mat-checkbox' is not a known element`.

I don't know Angular.

**Comment by urish** [comment]
Thanks!

Regarding the checkbox: you'd need to add `MatCheckboxModule` to the imports section in [`app.module.ts`](https://github.com/urish/tsquery-playground/blob/master/src/app/app.module.ts)

But I'm not sure if we even need one, is there a reason not to use TSX for parsing the AST in some cases? 

@DanielRosenwasser perhaps you can share some input here?

**Comment by dutzi** [comment]
@urish sure, thank you for making this tool!

**Comment by urish** [comment]
Closing due to inactivity. TSX support was added by d27464e.

**Pull request closed without merging**
